# Generated by Django 4.2.4 on 2023-08-05 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="DaysActivitie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
                ("list_of_things", models.CharField(max_length=200)),
                ("productivity_range", models.PositiveIntegerField()),
            ],
        ),
    ]
