# Generated by Django 4.2.4 on 2023-08-06 08:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="DaysActivitie",
            new_name="DaysActivities",
        ),
    ]
