# Generated by Django 4.2.4 on 2023-08-07 21:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0002_rename_daysactivitie_daysactivities"),
    ]

    operations = [
        migrations.CreateModel(
            name="showDate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateField()),
            ],
        ),
        migrations.AlterField(
            model_name="daysactivities",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="activities.showdate"
            ),
        ),
    ]
