# Generated by Django 4.2.4 on 2023-08-07 22:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("activities", "0004_alter_daysactivities_date_delete_showdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="daysactivities",
            name="date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
